[DiscreteCosseratMapping] Fixed small bug in the DiscreteCosseratMapping component inside init function.
SofaDefrost/Cosserat pull request #105
Opened 2024-04-05 15:09 UTC by adagolodjo

Fixed: Parent function of 'init' in DiscreteCosseratMapping was called very early, before the initialization of mechanical parameters such as position.

@EulalieCoevoet it's fixed.

2024-04-08 07:23 UTC, alxbilger requested changes

2024-04-08 07:23 UTC, alxbilger commented on examples/python3/cosserat/cosseratObject.py
> +    #                    forces=[0., -100., 0., 0., 0., 0.])
```suggestion
```

2024-04-08 07:23 UTC, alxbilger commented on examples/python3/cosserat/cosseratObject.py
> +    # collisionModel = cosserat.addCollisionModel()
```suggestion
```

2024-04-08 08:53 UTC, damienmarchal commented on src/Cosserat/mapping/DiscreteCosseratMapping.inl
> +    Inherit1::init();
"call super", anti-pattern detected. I'm curious to see if we can refactor :)

2024-04-10 06:59 UTC, alxbilger approved these changes

2024-04-10 06:59 UTC, merged