Apply new registration mechanism
SofaDefrost/Cosserat pull request #141
Opened 2024-11-29 18:00 UTC by bakpaul

This applies the new factory registration mechanism as introduced by [[All] ObjectFactory: Explicit components registration  #4429 ](https://github.com/sofa-framework/sofa/pull/4429)

In the process I've encountered a problem of consistency of namespace. I needed all of the registering methods to be in the `Cosserat` namespace. But a lot of SOFA namespace are used. This is bad practice, only the Cosserat namespace should be used in this plugin.

2024-12-02 08:35 UTC, bakpaul commented
Please test it on your side before merging.

2024-12-03 14:31 UTC, adagolodjo approved these changes

2024-12-03 14:34 UTC, adagolodjo reviewed
As it stands, I think the code is good. But, you're right, I'll try to compile it on my machine and test scenes before a possible merge.

2024-12-04 13:02 UTC, alxbilger reviewed
Overall, @adagolodjo could you take the opportunity to review all the Component descriptions? I see a lot of copy/paste.

2024-12-11 09:40 UTC, alxbilger commented on src/Cosserat/initCosserat.cpp
> +extern void registerCosseratNeedleSlidingConstraint(sofa::core::ObjectFactory* factory);
is `extern` keyword needed?

2024-12-24 08:19 UTC, adagolodjo commented on src/Cosserat/constraint/QPSlidingConstraint.cpp
> +namespace sofa::component::constraintset {
The PR works with examples I have in the tutorial folder. So for me, it's ok.

2024-12-24 08:26 UTC, adagolodjo commented
> Overall, @adagolodjo could you take the opportunity to review all the Component descriptions? I see a lot of copy/paste.

@alxbilger, This has been done in some pending PRs, and some of them are deprecated. So I'm trying to reactivate them as I go. Let's push this one before it becomes deprecated as well.

2025-01-06 13:06 UTC, alxbilger commented
@adagolodjo ok but remove the comments looking like:

```
////////////////////////////////////////////    FACTORY    //////////////////////////////////////////////
// Registering the component
// see: http://wiki.sofa-framework.org/wiki/ObjectFactory
// 1-RegisterObject("description") + .add<> : Register the component
// 2-.add<>(true) : Set default template
```

It's very related to this PR.

2025-01-08 08:28 UTC, alxbilger requested changes

2025-01-08 08:28 UTC, alxbilger commented on src/Cosserat/constraint/CosseratActuatorConstraint.cpp
> +void registerCosseratActuatorConstraint(sofa::core::ObjectFactory* factory)
The comments before must be removed as it is no longer consistent with the new mechanism. This has to be done everywhere

2025-01-08 16:34 UTC, adagolodjo commented on src/Cosserat/constraint/CosseratActuatorConstraint.cpp
> +void registerCosseratActuatorConstraint(sofa::core::ObjectFactory* factory)
Hi @alxbilger. 

It's done in this [PR](https://github.com/bakpaul/Cosserat/pull/1), @bakpaul, please can you merge it ?

2025-01-09 07:52 UTC, alxbilger commented on src/Cosserat/constraint/CosseratActuatorConstraint.cpp
> +void registerCosseratActuatorConstraint(sofa::core::ObjectFactory* factory)
no it was not done. I've done it in [this commit](https://github.com/SofaDefrost/Cosserat/pull/141/commits/373aa6957139fa0bbf00501e12b85219bbe9c4ee)

2025-01-09 08:36 UTC, alxbilger commented
@bakpaul @adagolodjo I took the liberty to:

- Remove all inconsistent comments
- Restore the previous formatting on some files. They were changed by mistake I think.
- Uniformize template specialization
- Make minor cleaning

I recommend a last review from you.


@adagolodjo I realized seconds ago that you did some of the changes in a dedicated PR. Sorry

2025-01-09 08:37 UTC, bakpaul commented
I'll take a look. In the mean(time, do I still need to merge https://github.com/bakpaul/Cosserat/pull/1 ?

2025-01-09 08:38 UTC, alxbilger commented
@bakpaul no it can be closed. I did not see this PR unfortunately.

2025-01-09 08:47 UTC, bakpaul commented on src/Cosserat/constraint/CosseratActuatorConstraint.cpp
> +template class SOFA_COSSERAT_API sofa::component::constraintset::CosseratActuatorConstraint<sofa::defaulttype::Vec3Types>;
What is the use of having this explicit template instantiation without  adding the external instantiation in the header ?

2025-01-09 08:50 UTC, alxbilger commented on src/Cosserat/constraint/CosseratActuatorConstraint.cpp
> +template class SOFA_COSSERAT_API sofa::component::constraintset::CosseratActuatorConstraint<sofa::defaulttype::Vec3Types>;
I am not sure. I think the external instantiation must be done in the header anyway. I just uniformized the explicit template instantiations for all components, but only in the cpp files.

2025-01-09 08:55 UTC, bakpaul commented on src/Cosserat/constraint/CosseratActuatorConstraint.cpp
> +template class SOFA_COSSERAT_API sofa::component::constraintset::CosseratActuatorConstraint<sofa::defaulttype::Vec3Types>;
Ok, would require another PR for this ! Then it is all good to me !

2025-01-09 08:58 UTC, alxbilger approved these changes

2025-01-09 08:58 UTC, merged